//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geoton.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geoton.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap afganistan {
            get {
                object obj = ResourceManager.GetObject("afganistan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap albania {
            get {
                object obj = ResourceManager.GetObject("albania", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alemania {
            get {
                object obj = ResourceManager.GetObject("alemania", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap andorra {
            get {
                object obj = ResourceManager.GetObject("andorra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap angola {
            get {
                object obj = ResourceManager.GetObject("angola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap antigua_y_barbuda {
            get {
                object obj = ResourceManager.GetObject("antigua_y_barbuda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arabia_saudita {
            get {
                object obj = ResourceManager.GetObject("arabia_saudita", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap argelia {
            get {
                object obj = ResourceManager.GetObject("argelia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap argentina {
            get {
                object obj = ResourceManager.GetObject("argentina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap armenia {
            get {
                object obj = ResourceManager.GetObject("armenia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap australia {
            get {
                object obj = ResourceManager.GetObject("australia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap austria {
            get {
                object obj = ResourceManager.GetObject("austria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap azerbaijan {
            get {
                object obj = ResourceManager.GetObject("azerbaijan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bahamas {
            get {
                object obj = ResourceManager.GetObject("bahamas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bahrein {
            get {
                object obj = ResourceManager.GetObject("bahrein", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bangladesh {
            get {
                object obj = ResourceManager.GetObject("bangladesh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barbados {
            get {
                object obj = ResourceManager.GetObject("barbados", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap belgica {
            get {
                object obj = ResourceManager.GetObject("belgica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap belice {
            get {
                object obj = ResourceManager.GetObject("belice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap benin {
            get {
                object obj = ResourceManager.GetObject("benin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bielorrusia {
            get {
                object obj = ResourceManager.GetObject("bielorrusia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bolivia {
            get {
                object obj = ResourceManager.GetObject("bolivia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bosnia_y_herzegovina {
            get {
                object obj = ResourceManager.GetObject("bosnia_y_herzegovina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botsuana {
            get {
                object obj = ResourceManager.GetObject("botsuana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brasil {
            get {
                object obj = ResourceManager.GetObject("brasil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brunei {
            get {
                object obj = ResourceManager.GetObject("brunei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bulgaria {
            get {
                object obj = ResourceManager.GetObject("bulgaria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap burkina_faso {
            get {
                object obj = ResourceManager.GetObject("burkina_faso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap burundi {
            get {
                object obj = ResourceManager.GetObject("burundi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butan {
            get {
                object obj = ResourceManager.GetObject("butan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cabo_verde {
            get {
                object obj = ResourceManager.GetObject("cabo_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camboya {
            get {
                object obj = ResourceManager.GetObject("camboya", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camerun {
            get {
                object obj = ResourceManager.GetObject("camerun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap canada {
            get {
                object obj = ResourceManager.GetObject("canada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chad {
            get {
                object obj = ResourceManager.GetObject("chad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checa_republica {
            get {
                object obj = ResourceManager.GetObject("checa_republica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chile {
            get {
                object obj = ResourceManager.GetObject("chile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap china {
            get {
                object obj = ResourceManager.GetObject("china", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chipre {
            get {
                object obj = ResourceManager.GetObject("chipre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chipre_republica_turca_del_norte_de_chipre {
            get {
                object obj = ResourceManager.GetObject("chipre_republica_turca_del_norte_de_chipre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colombia {
            get {
                object obj = ResourceManager.GetObject("colombia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap comoras {
            get {
                object obj = ResourceManager.GetObject("comoras", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap congo_brazzaville {
            get {
                object obj = ResourceManager.GetObject("congo_brazzaville", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap congo_republica_democratica {
            get {
                object obj = ResourceManager.GetObject("congo_republica_democratica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corea_del_norte {
            get {
                object obj = ResourceManager.GetObject("corea_del_norte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap corea_del_sur {
            get {
                object obj = ResourceManager.GetObject("corea_del_sur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap costa_de_marfil {
            get {
                object obj = ResourceManager.GetObject("costa_de_marfil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap costa_rica {
            get {
                object obj = ResourceManager.GetObject("costa_rica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap croacia {
            get {
                object obj = ResourceManager.GetObject("croacia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cuba {
            get {
                object obj = ResourceManager.GetObject("cuba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dinamarca {
            get {
                object obj = ResourceManager.GetObject("dinamarca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dominica {
            get {
                object obj = ResourceManager.GetObject("dominica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ecuador {
            get {
                object obj = ResourceManager.GetObject("ecuador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap egipto {
            get {
                object obj = ResourceManager.GetObject("egipto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap el_salvador {
            get {
                object obj = ResourceManager.GetObject("el_salvador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emiratos_arabes_unidos {
            get {
                object obj = ResourceManager.GetObject("emiratos_arabes_unidos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eritrea {
            get {
                object obj = ResourceManager.GetObject("eritrea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eslovaquia {
            get {
                object obj = ResourceManager.GetObject("eslovaquia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eslovenia {
            get {
                object obj = ResourceManager.GetObject("eslovenia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap españa {
            get {
                object obj = ResourceManager.GetObject("españa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap estados_unidos {
            get {
                object obj = ResourceManager.GetObject("estados_unidos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap estonia {
            get {
                object obj = ResourceManager.GetObject("estonia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap etiopia {
            get {
                object obj = ResourceManager.GetObject("etiopia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fiji {
            get {
                object obj = ResourceManager.GetObject("fiji", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filipinas {
            get {
                object obj = ResourceManager.GetObject("filipinas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap finlandia {
            get {
                object obj = ResourceManager.GetObject("finlandia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap francia {
            get {
                object obj = ResourceManager.GetObject("francia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gabon {
            get {
                object obj = ResourceManager.GetObject("gabon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gambia {
            get {
                object obj = ResourceManager.GetObject("gambia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap georgia {
            get {
                object obj = ResourceManager.GetObject("georgia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ghana {
            get {
                object obj = ResourceManager.GetObject("ghana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap granada {
            get {
                object obj = ResourceManager.GetObject("granada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grecia {
            get {
                object obj = ResourceManager.GetObject("grecia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guatemala {
            get {
                object obj = ResourceManager.GetObject("guatemala", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guinea {
            get {
                object obj = ResourceManager.GetObject("guinea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guinea_bissau {
            get {
                object obj = ResourceManager.GetObject("guinea_bissau", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guinea_ecuatorial {
            get {
                object obj = ResourceManager.GetObject("guinea_ecuatorial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guyana {
            get {
                object obj = ResourceManager.GetObject("guyana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haiti {
            get {
                object obj = ResourceManager.GetObject("haiti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hidrosoft_s {
            get {
                object obj = ResourceManager.GetObject("Hidrosoft_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap honduras {
            get {
                object obj = ResourceManager.GetObject("honduras", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hungria {
            get {
                object obj = ResourceManager.GetObject("hungria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap india {
            get {
                object obj = ResourceManager.GetObject("india", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap indonesia {
            get {
                object obj = ResourceManager.GetObject("indonesia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap irak {
            get {
                object obj = ResourceManager.GetObject("irak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iran {
            get {
                object obj = ResourceManager.GetObject("iran", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap irlanda {
            get {
                object obj = ResourceManager.GetObject("irlanda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap islandia {
            get {
                object obj = ResourceManager.GetObject("islandia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap islas_marshall {
            get {
                object obj = ResourceManager.GetObject("islas_marshall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap islas_salomon {
            get {
                object obj = ResourceManager.GetObject("islas_salomon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap israel {
            get {
                object obj = ResourceManager.GetObject("israel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap italia {
            get {
                object obj = ResourceManager.GetObject("italia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap jamaica {
            get {
                object obj = ResourceManager.GetObject("jamaica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap japon {
            get {
                object obj = ResourceManager.GetObject("japon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap jordania {
            get {
                object obj = ResourceManager.GetObject("jordania", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kazajstan {
            get {
                object obj = ResourceManager.GetObject("kazajstan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kenia {
            get {
                object obj = ResourceManager.GetObject("kenia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kirguiztan {
            get {
                object obj = ResourceManager.GetObject("kirguiztan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kiribati {
            get {
                object obj = ResourceManager.GetObject("kiribati", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kuwait {
            get {
                object obj = ResourceManager.GetObject("kuwait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap laos {
            get {
                object obj = ResourceManager.GetObject("laos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lesotho {
            get {
                object obj = ResourceManager.GetObject("lesotho", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap letonia {
            get {
                object obj = ResourceManager.GetObject("letonia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap libano {
            get {
                object obj = ResourceManager.GetObject("libano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap liberia {
            get {
                object obj = ResourceManager.GetObject("liberia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap libia {
            get {
                object obj = ResourceManager.GetObject("libia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap liechtenstein {
            get {
                object obj = ResourceManager.GetObject("liechtenstein", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lituania {
            get {
                object obj = ResourceManager.GetObject("lituania", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap luxemburgo {
            get {
                object obj = ResourceManager.GetObject("luxemburgo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macedonia {
            get {
                object obj = ResourceManager.GetObject("macedonia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap madagascar {
            get {
                object obj = ResourceManager.GetObject("madagascar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap malasia {
            get {
                object obj = ResourceManager.GetObject("malasia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap malawi {
            get {
                object obj = ResourceManager.GetObject("malawi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maldivas {
            get {
                object obj = ResourceManager.GetObject("maldivas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mali {
            get {
                object obj = ResourceManager.GetObject("mali", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap malta {
            get {
                object obj = ResourceManager.GetObject("malta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap marruecos {
            get {
                object obj = ResourceManager.GetObject("marruecos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mauricio {
            get {
                object obj = ResourceManager.GetObject("mauricio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mauritania {
            get {
                object obj = ResourceManager.GetObject("mauritania", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mexico {
            get {
                object obj = ResourceManager.GetObject("mexico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap micronesia {
            get {
                object obj = ResourceManager.GetObject("micronesia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moldavia {
            get {
                object obj = ResourceManager.GetObject("moldavia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap monaco {
            get {
                object obj = ResourceManager.GetObject("monaco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mongolia {
            get {
                object obj = ResourceManager.GetObject("mongolia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap montenegro {
            get {
                object obj = ResourceManager.GetObject("montenegro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap montserrat {
            get {
                object obj = ResourceManager.GetObject("montserrat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mozambique {
            get {
                object obj = ResourceManager.GetObject("mozambique", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap myanmar {
            get {
                object obj = ResourceManager.GetObject("myanmar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap namibia {
            get {
                object obj = ResourceManager.GetObject("namibia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nauru {
            get {
                object obj = ResourceManager.GetObject("nauru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nepal {
            get {
                object obj = ResourceManager.GetObject("nepal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nicaragua {
            get {
                object obj = ResourceManager.GetObject("nicaragua", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap niger {
            get {
                object obj = ResourceManager.GetObject("niger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nigeria {
            get {
                object obj = ResourceManager.GetObject("nigeria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap none {
            get {
                object obj = ResourceManager.GetObject("none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap noruega {
            get {
                object obj = ResourceManager.GetObject("noruega", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nueva_zelanda {
            get {
                object obj = ResourceManager.GetObject("nueva_zelanda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap oman {
            get {
                object obj = ResourceManager.GetObject("oman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paises_bajos {
            get {
                object obj = ResourceManager.GetObject("paises_bajos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pakistan {
            get {
                object obj = ResourceManager.GetObject("pakistan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap palau {
            get {
                object obj = ResourceManager.GetObject("palau", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap palestina {
            get {
                object obj = ResourceManager.GetObject("palestina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panama {
            get {
                object obj = ResourceManager.GetObject("panama", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap papua_nueva_guinea {
            get {
                object obj = ResourceManager.GetObject("papua_nueva_guinea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paraguay {
            get {
                object obj = ResourceManager.GetObject("paraguay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap peru {
            get {
                object obj = ResourceManager.GetObject("peru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap polonia {
            get {
                object obj = ResourceManager.GetObject("polonia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap portugal {
            get {
                object obj = ResourceManager.GetObject("portugal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pregunta {
            get {
                object obj = ResourceManager.GetObject("pregunta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pregunta_chida {
            get {
                object obj = ResourceManager.GetObject("pregunta_chida", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap puerto_rico {
            get {
                object obj = ResourceManager.GetObject("puerto_rico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap qatar {
            get {
                object obj = ResourceManager.GetObject("qatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reino_unido {
            get {
                object obj = ResourceManager.GetObject("reino_unido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap republica_centroafricana {
            get {
                object obj = ResourceManager.GetObject("republica_centroafricana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap republica_dominicana {
            get {
                object obj = ResourceManager.GetObject("republica_dominicana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ruanda {
            get {
                object obj = ResourceManager.GetObject("ruanda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rumania {
            get {
                object obj = ResourceManager.GetObject("rumania", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rusia {
            get {
                object obj = ResourceManager.GetObject("rusia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sahara_occidental {
            get {
                object obj = ResourceManager.GetObject("sahara_occidental", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap samoa {
            get {
                object obj = ResourceManager.GetObject("samoa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap san_cristobal_y_nieves {
            get {
                object obj = ResourceManager.GetObject("san_cristobal_y_nieves", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap san_marino {
            get {
                object obj = ResourceManager.GetObject("san_marino", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap san_vicente_y_las_granadinas {
            get {
                object obj = ResourceManager.GetObject("san_vicente_y_las_granadinas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap santa_helena {
            get {
                object obj = ResourceManager.GetObject("santa_helena", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap santa_lucia {
            get {
                object obj = ResourceManager.GetObject("santa_lucia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap santo_tome_y_principe {
            get {
                object obj = ResourceManager.GetObject("santo_tome_y_principe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap senegal {
            get {
                object obj = ResourceManager.GetObject("senegal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap serbia {
            get {
                object obj = ResourceManager.GetObject("serbia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap seychelles {
            get {
                object obj = ResourceManager.GetObject("seychelles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sierra_leona {
            get {
                object obj = ResourceManager.GetObject("sierra_leona", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap singapur {
            get {
                object obj = ResourceManager.GetObject("singapur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap siria {
            get {
                object obj = ResourceManager.GetObject("siria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap somalia {
            get {
                object obj = ResourceManager.GetObject("somalia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap somaliland {
            get {
                object obj = ResourceManager.GetObject("somaliland", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sri_lanka {
            get {
                object obj = ResourceManager.GetObject("sri_lanka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sudafrica {
            get {
                object obj = ResourceManager.GetObject("sudafrica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sudan {
            get {
                object obj = ResourceManager.GetObject("sudan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap suecia {
            get {
                object obj = ResourceManager.GetObject("suecia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap suiza {
            get {
                object obj = ResourceManager.GetObject("suiza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap surinam {
            get {
                object obj = ResourceManager.GetObject("surinam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap swazilandia {
            get {
                object obj = ResourceManager.GetObject("swazilandia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tailandia {
            get {
                object obj = ResourceManager.GetObject("tailandia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taiwan {
            get {
                object obj = ResourceManager.GetObject("taiwan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tanzania {
            get {
                object obj = ResourceManager.GetObject("tanzania", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tayikistan {
            get {
                object obj = ResourceManager.GetObject("tayikistan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap timor_oriental {
            get {
                object obj = ResourceManager.GetObject("timor_oriental", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap togo {
            get {
                object obj = ResourceManager.GetObject("togo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tokelau {
            get {
                object obj = ResourceManager.GetObject("tokelau", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tonga {
            get {
                object obj = ResourceManager.GetObject("tonga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transnistria {
            get {
                object obj = ResourceManager.GetObject("transnistria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trinidad_y_tobago {
            get {
                object obj = ResourceManager.GetObject("trinidad_y_tobago", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tunez {
            get {
                object obj = ResourceManager.GetObject("tunez", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap turkmenistan {
            get {
                object obj = ResourceManager.GetObject("turkmenistan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap turquia {
            get {
                object obj = ResourceManager.GetObject("turquia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tuvalu {
            get {
                object obj = ResourceManager.GetObject("tuvalu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ucrania {
            get {
                object obj = ResourceManager.GetObject("ucrania", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap uganda {
            get {
                object obj = ResourceManager.GetObject("uganda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap uruguay {
            get {
                object obj = ResourceManager.GetObject("uruguay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap uzbekistan {
            get {
                object obj = ResourceManager.GetObject("uzbekistan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vanuatu {
            get {
                object obj = ResourceManager.GetObject("vanuatu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vaticano {
            get {
                object obj = ResourceManager.GetObject("vaticano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap venezuela {
            get {
                object obj = ResourceManager.GetObject("venezuela", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vietnam {
            get {
                object obj = ResourceManager.GetObject("vietnam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yemen {
            get {
                object obj = ResourceManager.GetObject("yemen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yibuti {
            get {
                object obj = ResourceManager.GetObject("yibuti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zaire {
            get {
                object obj = ResourceManager.GetObject("zaire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zambia {
            get {
                object obj = ResourceManager.GetObject("zambia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zimbabwe {
            get {
                object obj = ResourceManager.GetObject("zimbabwe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
